name: Check Style Code

on:
  push:
    branches:
      - asd

  pull_request:
    branches:
      - asd

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      # �������� ����
      - name: Checkout code
        uses: actions/checkout@v3

      # ��������� .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.404' # ������� ������ ������ SDK

      # ��������� StyleCop.Analyzers
      - name: Install StyleCop.Analyzers
        run: |
          dotnet add package StyleCop.Analyzers --prerelease

      # ������ ������� (����������� ����� ��������)
      - name: Build project
        run: |
          dotnet build --no-restore

      # �������� ����� ���� � ������� StyleCop
      - name: Run StyleCop Analysis
        run: |
          dotnet build -warnaserror
